### PR TITLE
Tower postinstall config

### PR DESCRIPTION
**Pull request by vvaldez**
This PR contains #41 commit so I can test them together. I added references to the postinstall into the tower_config. I renamed some variables to make more sense since this repo has more than just provision playbooks.

To test set these variables:
```
tower_config: true
tower_workflow_job_launch: true
tower_project_provision_and_configure_url: "https://github.com/vvaldez/summit-2017-ocp-operator.git"
tower_project_provision_and_configure_branch: "tower-postinstall-config"
```

### CODE REVIEW

**Comment by sabre1041** [comment]
I know its not part of this PR specifically, but we really should set the following variable to false as a default 

```
tower_workflow_job_launch: false
```

For testing scenarios, it can be set to true, but since students will be walking through the process themselves, it should be false by default

**Comment by vvaldez** [comment]
@sabre1041 sure I'll change it. IMHO this variable doesn't matter until `tower_config: true` but in any case both of these are only meant for us, so false makes sense. We could also have a `testing: true` variable that, when set to true, sets these both to true? I'm just lazy and only wanted to override one variable :D

**Comment by sabre1041** [comment]
@vvaldez LGTM

@scollier please go ahead and review. You will need to set the following in the `tower_vars.yml` file

```
tower_project_provision_and_configure_url: "https://github.com/vvaldez/summit-2017-ocp-operator.git"
tower_project_provision_and_configure_branch: "tower-postinstall-config"
```

**Comment by scollier** [comment]
This run failed for me.  Can you please summarize in the instructions what all you expect to be done after this PR has run?  Combining the other PR with this one is a little confusing.  For example, in #41 there are only 2 templates that exist.  Now, running this one, there are 3, and I need to add a 4th.  Expected results will help.  This is my failure message:

```
TASK [Provision AWS Instances] *************************************************
13:55:18
failed: [localhost] (item={u'image': u'ami-9e3417fb', u'meta': {u'node_labels': {u'type': u'infra', u'zone': u'default'}, u'node_type': u'master'}, u'type': u't2.large', u'name': u'master', u'groups': [u'masters', u'osev3', u'creator_"scollier"']}) => {"failed": true, "item": {"groups": ["masters", "osev3", "creator_\"scollier\""], "image": "ami-9e3417fb", "meta": {"node_labels": {"type": "infra", "zone": "default"}, "node_type": "master"}, "name": "master", "type": "t2.large"}, "module_stderr": "sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
failed: [localhost] (item={u'image': u'ami-9e3417fb', u'meta': {u'node_labels': {u'type': u'app', u'zone': u'default'}, u'node_type': u'node'}, u'type': u't2.xlarge', u'name': u'node1', u'groups': [u'nodes', u'osev3', u'creator_"scollier"']}) => {"failed": true, "item": {"groups": ["nodes", "osev3", "creator_\"scollier\""], "image": "ami-9e3417fb", "meta": {"node_labels": {"type": "app", "zone": "default"}, "node_type": "node"}, "name": "node1", "type": "t2.xlarge"}, "module_stderr": "sudo: effective uid is not 0, is /usr/bin/sudo on a file system with the 'nosuid' option set or an NFS file system without root privileges?\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by scollier** [comment]
I tried this again without creating an extra template, that was included in the PR. So, here are the results as I see them, I'm not 100% sure if these are expected:

1. I had the "traditional" OCP interface, not the service catalog.
2. I did get a CF template
3. I did deploy CF manually, using the template, and it failed.

This is the message from the stateful set creation:

```
create Pod cloudforms-0 in StatefulSet cloudforms failed error: pods "cloudforms-0" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]
25 times in the last 
```

**Comment by vvaldez** [comment]
@scollier I believe you just need to confirm that the postinstall playbook ran, so make sure the following are covered by this PR:

- There is a 3rd job template in Tower "Deploy-3-Post-Install" that kicks off the playbook "openshift_postinstall.yml" on the master
- This 3rd job template is connected to the workflow template as the last job template to kick off
- Per #41 verify the following:
```
Once successful, log in to OpenShift and confirm the majority of the templates have been removed keeping the Cake PHP + MySQL Persistent and cloudforms templates are present.
```

**Comment by scollier** [comment]
@vvaldez I can confirm those actions happened.

One note, for the last line in your comment, CFME is there, but it's labeled as "Uncatagorized". 

Everything else LGTM.  Merge when ready.

Ack on troubleshooting CFME in another PR>

**Pull request merged**
