### PR TITLE
Update credential modules to use tower-cli

### PR DESCRIPTION
**Pull request by vvaldez**
The best way to test a full run is to run `aws_lab_launch.yml` using an AMI that has been recently built (with no credentials built in).

To test thoroughly, do the following:

- Specify the new variable `tower_credential_machine_ssh_key_data_file` (this was previously `tower_credential_machine_ssh_key_data`) and should be the local filename and path to your private key either on the CLI via -e or in a secrets file
- Launch `aws_lab_launch.yml` with `tower_config: none`
- Login with your student ID (user-X) and whatever password you set with `tower_password`
- Verify no Machine or Cloud credentials are baked in
- Redpeloy again but this time with `tower_config: self`
- Login and verify credentials are added for Machine and Cloud
- Launch `Self` job to ensure all job and workflow templates are created
- Optionally run `tower_config: full` or `tower_config: test` to verify

### CODE REVIEW

**Comment by vvaldez** [comment]
@scollier ready to test. FYI in response to your comment, there is no need to specify `tower_credential_cloud_config=true` or `tower_credential_machine_config=true` as these are not default unless you specify `tower_config: none`.

**Comment by scollier** [comment]
@vvaldez i think it would be helpful moving forward, for PRs, if we just drop an example playbook run command in there with the appropriate variables set.

**Comment by scollier** [comment]
LGTM.  I tested with "none" and "self".

**Comment by vvaldez** [comment]
@scollier good idea, I'll do that. For reference here's the command I used for this run, is this what you mean? I agree though, we should have a standard format for PRs.

Run with:
```
ansible-playbook aws_lab_launch.yml -e @vvaldez-secrets-sysdeseng.yml -e @aws-us-west1-syseng.yml  -e student_count_start=$(( TOWERVER += 1 )) -e student_count_end=$(( TOWERVER ))
```

With the following variables set:
```
ec2_access_key: <redacted> 
ec2_secret_key: <redacted>
tower_password: <redacted>
tower_credential_machine_ssh_key_data_file: <redacted>
tower_ami_id: <redacted>
oc_ami_id: <redacted>
```

Along with the normal aws variable data (_vpc, _route_table, _subnet_id, etc). Like this?

**Comment by scollier** [comment]
@vvaldez thanks for the updates here.  I'll likely get around to testing this sometime next week.

**Pull request merged**
