### PR TITLE
WIP: Postinstall Activities

### PR DESCRIPTION
**Pull request by sabre1041**
* Removal of HTTP/Git Server
* Added CFME template to OpenShift
* Removal of air gapped considerations

### CODE REVIEW

**Comment by sabre1041** [comment]
@scollier I see that the contents of the postinstall was removed in this PR

https://github.com/sabre1041/managing-ocp-install-beyond/pull/35/

Would you like to start with a fresh set of files for the updated postinstall activities?

**Comment by scollier** [comment]
@sabre1041 our intent was not to disrupt what you were doing. Simply to clean up the repo. Please move whatever files around you see fit.

**Comment by sabre1041** [comment]
@scollier no worries. I'll close this PR and submit a new one with everything up to the service catalog stuff first thing tomorrow EMEA time. that way @vvaldez can hook it up to the workflow.

The rest of the items will come with the service catalog/app afterward

**Comment by sabre1041** [comment]
Closing in favor of #41

**Pull request closed without merging**
